/**
 * Romantic Surprise Website - Placeholder Creator
 * Generates lightweight, valid media files for images, videos, and music.
 */

const fs = require('fs');
const path = require('path');

const IMAGE_DIR = path.join(__dirname, 'images');
const VIDEO_DIR = path.join(__dirname, 'videos');
const MUSIC_DIR = path.join(__dirname, 'music');

// Minimal 1x1 PNGs in base64
// 1. Rose Gold (#b76e79)
// 2. Light Rose Gold (#d4a2a9)
// 3. Gold Accent (#d4af37)
// 4. Luxury Dark Purple (#1c0f16)
// 5. Pale Champagne (#ebd3be)
const MOCK_PNGS = [
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mPsPnC+HgAFagIi/GexYQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mPsPXVtHgAGFwI3O9vYiwAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8P1f2HgAGKgI8q5R88QAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP807K6HgAGWgI4/06ePQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/zX3HgAGGgI52/xWtwAAAABJRU5ErkJggg=='
];

// Minimal 1-second silent MP3 file in base64
const MOCK_MP3 = '//uQxAAAAAAAAAAAAASW5mbwAAAA8AAAAFAAAC7gALCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLD///AAAAhExBTUUzLjk4cgG0AAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//uQZAAAC8kNXmAMAEB3IXxMAQAEAAABXgAAAIAAADSAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//uQZAAAC8kNXmAMAEB3IXxMAQAEAAABXgAAAIAAADSAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

// Minimal 1-second black MP4 video in base64
const MOCK_MP4 = 'AAAAIGZ0eXBpc29tAAAAAGlzb21pc28ybXA0MQAAAAhmcmVlAAAAG21kYXTeBAAD+gPDCGaQAEAD//7+GFyWZgAAMDBtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAD6AAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAJIdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAJIAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAJRbWRpYQAAACxtZGhkAAAAAAAAAAAAAAAAAAAD6AAAAPoBwgAAAAAAaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAHhtbmYAAAAUdm1oZAAAAAAAAAAAAAAAAAAAAChkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAadzdGJsAAAAanN0c2QAAAAAAAAAAQAAAFphdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAgACABIAAAASAAAAAAAEABhdmNDAWQAMv/hABhnRGQAyqAoAm8EQAAAAwBAAAADAGQeLGUgAQAGaGlzdHIAAAAAFHN0dHMAAAAAAAAAAQAAAAEAAAPoAAAAFHN0c3oAAAAAAAAAAQAAAAMAAAAUc3RjbwAAAAAAAAABAAAAlg==';

function createDirectories() {
  [IMAGE_DIR, VIDEO_DIR, MUSIC_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
}

function writeMockAssets() {
  createDirectories();

  // Create 5 images
  MOCK_PNGS.forEach((base64, index) => {
    const filename = `${index + 1}.png`;
    const filePath = path.join(IMAGE_DIR, filename);
    fs.writeFileSync(filePath, Buffer.from(base64, 'base64'));
    console.log(`Created mock image: ${filePath}`);
  });

  // Create 2 videos
  for (let i = 1; i <= 2; i++) {
    const filename = `${i}.mp4`;
    const filePath = path.join(VIDEO_DIR, filename);
    fs.writeFileSync(filePath, Buffer.from(MOCK_MP4, 'base64'));
    console.log(`Created mock video: ${filePath}`);
  }

  // Create 1 music track
  const musicPath = path.join(MUSIC_DIR, '1.mp3');
  fs.writeFileSync(musicPath, Buffer.from(MOCK_MP3, 'base64'));
  console.log(`Created mock music track: ${musicPath}`);

  console.log('Mock asset creation complete.');
}

writeMockAssets();
